# Your info

Full name: Keyvan Dadashzadeh

Student ID: 97522148

# Q1. Hopfield

In [ ]:
# Q1.1_graded
# Do not change the above line.

# This cell is for your imports.

import numpy as np
import matplotlib.pyplot as plt

def process_weights(patterns, weights_dimension):
  weights = np.ndarray(weights_dimension, buffer=np.full(weights_dimension[0] * weights_dimension[1], 0), dtype=float)
  for pattern in patterns: 
      for index_i in range(weights_dimension[0]):
        for index_j in range(index_i): 
          weights[index_i, index_j] += pattern[index_i] * pattern[index_j]
          weights[index_j, index_i] = weights[index_i, index_j]

  np.fill_diagonal(weights, 0)
  return weights


def process_energy(patterns, weights, weights_dimension):
  energy = np.ndarray((len(patterns), 1), buffer=np.full(len(patterns), 0), dtype=float)
  # energy = [0 for i in range(len(patterns))]
  for index, pattern in enumerate(patterns):
    for index_i in range(weights_dimension[0]):
      for index_j in range(weights_dimension[1]):
        energy[index] += weights[index_i][index_j] * pattern[index_i] * pattern[index_j]
  return (-1 * energy)/2


def sign(pattern, weights):
  return np.sign(np.dot(pattern, weights))


patterns = [
    [1, 1, 1, 1],
    [-1, -1, -1, -1],
    [1, 1, -1, -1],
    [-1, -1, 1, 1]
]
weights = process_weights(patterns, (4, 4))
print(weights)
energy = process_energy(patterns, weights, (4, 4))       
print(energy)

[[0. 4. 0. 0.]
 [4. 0. 0. 0.]
 [0. 0. 0. 4.]
 [0. 0. 4. 0.]]
[[-8.]
 [-8.]
 [-8.]
 [-8.]]


## Q1.2

In [ ]:
# Q1.2_graded
# Do not change the above line.

# This cell is for your imports.

import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Q1.2_graded
# Do not change the above line.


def process_weights(patterns, weights_dimension):
  weights = np.ndarray(weights_dimension, buffer=np.full(weights_dimension[0] * weights_dimension[1], 0), dtype=float)
  for pattern in patterns: 
      for index_i in range(weights_dimension[0]):
        for index_j in range(index_i): 
          weights[index_i, index_j] += pattern[index_i] * pattern[index_j]
          weights[index_j, index_i] = weights[index_i, index_j]

  np.fill_diagonal(weights, 0)
  return weights


def process_energy(patterns, weights, weights_dimension):
  energy = np.ndarray((len(patterns), 1), buffer=np.full(len(patterns), 0), dtype=float)
  # energy = [0 for i in range(len(patterns))]
  for index, pattern in enumerate(patterns):
    for index_i in range(weights_dimension[0]):
      for index_j in range(weights_dimension[1]):
        energy[index] = weights[index_i][index_j] * pattern[index_i] * pattern[index_j]
  return energy/2


def sign(pattern, weights):
  return np.sign(np.dot(pattern, weights))


patterns = [
    [1, -1, 1, -1, 1, -1],
    [1, 1, 1, -1, -1, -1]
]
weights = process_weights(patterns, (6, 6))
print(weights)
print(sign([1, 1, 1, -1, -1, -1], weights))
print(sign([-1, 1, 1, -1, -1, -1], weights))
energy = process_energy(patterns, weights, (6, 6))       
print(energy)

[[ 0.  0.  2. -2.  0. -2.]
 [ 0.  0.  0.  0. -2.  0.]
 [ 2.  0.  0. -2.  0. -2.]
 [-2.  0. -2.  0.  0.  2.]
 [ 0. -2.  0.  0.  0.  0.]
 [-2.  0. -2.  2.  0.  0.]]
[ 1.  1.  1. -1. -1. -1.]
[ 1.  1.  1. -1. -1. -1.]
[[0.]
 [0.]]


## Q1.3

In [ ]:
# Q1.3_graded
# Do not change the above line.

# This cell is for your imports.

!wget "https://www.cufonfonts.com/download/rf/arial"
!pwd
!mkdir -p download_data
!mv arial download_data/
!cd download_data
!unzip download_data/arial -d download_data/
!mv download_data/ARIAL.TTF /usr/share/fonts/truetype/
!cd ..
!rm -rf download_data/

--2021-06-04 02:27:51--  https://www.cufonfonts.com/download/rf/arial
Resolving www.cufonfonts.com (www.cufonfonts.com)... 172.67.73.52, 104.26.8.47, 104.26.9.47, ...
Connecting to www.cufonfonts.com (www.cufonfonts.com)|172.67.73.52|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.cufonfonts.com/download/font/arial [following]
--2021-06-04 02:27:52--  https://www.cufonfonts.com/download/font/arial
Reusing existing connection to www.cufonfonts.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 3834335 (3.7M) [application/zip]
Saving to: ‘arial’

arial               100%[===================>]   3.66M  --.-KB/s    in 0.1s    

2021-06-04 02:27:52 (29.1 MB/s) - ‘arial’ saved [3834335/3834335]

/content
Archive:  download_data/arial
  inflating: download_data/ARIAL.TTF  
  inflating: download_data/ARIALN.TTF  
  inflating: download_data/ARIALI 1.TTF  
  inflating: download_data/ARIALI.TTF  
  inflating: download_data/ARIALNI.TTF  
  in

In [ ]:
# Q1.3_graded
# Do not change the above line.

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image, ImageFont
import os
# This cell is for your codes.


def gen_patterns(font_size):
  font = ImageFont.truetype("/usr/share/fonts/truetype/ARIAL.TTF", font_size)
  max_pixel = (-1,)
  raw_patterns = []
  for char in "ABCDEFGHIJ":
      im = Image.Image()._new(font.getmask(char))
      pixels = np.array(im.getdata())
      if pixels.shape[0] > max_pixel[0]:
        max_pixel = pixels.shape
      raw_patterns.append(pixels)


  equal_patterns = []
  for raw_pattern in raw_patterns:
    if max_pixel[0] == len(raw_pattern):
      continue
    
    shift_size = max_pixel[0] - len(raw_pattern)
    
    equal_pattern = np.zeros(max_pixel)
    equal_pattern[int(shift_size/2):int(len(raw_pattern) + shift_size/2)] = raw_pattern
    equal_pattern = np.where(equal_pattern > 0, 1, equal_pattern)
    equal_patterns.append(np.where(equal_pattern == 0, -1, equal_pattern))

  return equal_patterns


def convert_to_noisy_pattern(original_patterns, noise_rate):
  max_pixel = original_patterns[0].shape
  final_patterns = []

  patterns = original_patterns.copy()

  number_of_noise = int(max_pixel[0] * noise_rate)

  for index, equal_pattern in enumerate(patterns):
    random_numbers = np.random.randint(max_pixel[0], size=number_of_noise)
    for i in random_numbers:
      patterns[index][i] = equal_pattern[i] * -1
    final_patterns.append(equal_pattern)


  return final_patterns


def process_weights(patterns, weights_dimension):
  weights = np.ndarray(weights_dimension, buffer=np.full(weights_dimension[0] * weights_dimension[1], 0), dtype=float)
  for pattern in patterns: 
    for index_i in range(weights_dimension[0]):
      for index_j in range(index_i, weights_dimension[0]): 
        weights[index_i, index_j] += pattern[index_i] * pattern[index_j]
        weights[index_j, index_i] = weights[index_i, index_j]

  np.fill_diagonal(weights, 0)
  return weights

def sign(pattern, weights):
  return np.sign(np.dot(pattern, weights))

def accu(first, second):
  return np.sum(first == second) / first.shape[0]

font_16_patterns = gen_patterns(16)
font_32_patterns = gen_patterns(32)
font_64_patterns = gen_patterns(64)


font_16_weights = process_weights(font_16_patterns, (font_16_patterns[0].shape[0], font_16_patterns[0].shape[0]))
font_32_weights = process_weights(font_32_patterns, (font_32_patterns[0].shape[0], font_32_patterns[0].shape[0]))
font_64_weights = process_weights(font_64_patterns, (font_64_patterns[0].shape[0], font_64_patterns[0].shape[0]))


noises = [0.1, 0.3, 0.6]

def eval_acc(patterns, noisy_patterns, weights):
  sum = 0
  for index, noisy_pattern in enumerate(noisy_patterns):
    signed = sign(noisy_pattern, weights)
    sum += accu(patterns[index], signed)
  return sum / len(noisy_patterns)

for noise in noises:
  print('-'*20 + ' start noise' + str(noise) + ' ' + '-'*20)

  font_16_patterns_noise = convert_to_noisy_pattern(font_16_patterns, noise)
  print(eval_acc(font_16_patterns, font_16_patterns_noise, font_16_weights))

  font_32_patterns_noise = convert_to_noisy_pattern(font_32_patterns, noise)
  print(eval_acc(font_32_patterns, font_32_patterns_noise, font_32_weights))

  font_64_patterns_noise = convert_to_noisy_pattern(font_64_patterns, noise)
  print(eval_acc(font_64_patterns, font_64_patterns_noise, font_64_weights))

  print('-'*20 + ' end noise' + str(noise) + ' ' + '-'*20)


--------------------start noise0.1--------------------
0.8746438746438745
0.8790338164251207
0.8531018518518518
--------------------end noise0.1--------------------
--------------------start noise0.3--------------------
0.6894586894586896
0.6983574879227054
0.6936574074074074
--------------------end noise0.3--------------------
--------------------start noise0.6--------------------
0.5527065527065527
0.5412560386473431
0.5553703703703704
--------------------end noise0.6--------------------


# <font color='red'>Submission</font>

1. Sign up in [Gradescope](https://www.gradescope.com) with proper name and student ID and use the following code to join the class: <font color='green'>**D5372R**</font>
2. Fill in your full name (seperated by single spaces) and student ID in the beginning of this notebook.
3. After you're done with this notebook, you should do the following:
  - Clear all outputs of the notebook.
  ![clear all outputs](https://i.ibb.co/y6FrttB/Screen-Shot-2021-03-21-at-01-51-42.png)
  - Run all of the cells (if you skipped a question just leave the cell unchanged), and make sure all of your outputs are correct.
  ![run all](https://i.ibb.co/cgRcBZ0/Screen-Shot-2021-03-21-at-01-54-58.png)
  - Save your notebook.
  - If you're using Colab, download your notebook.
  ![download ipynb](https://i.ibb.co/2KxYM6K/Screen-Shot-2021-03-21-at-02-03-50.png)
  - Put the notebook file you just downloaded and `convert.py` in the same folder run the following command:
  ```bash
  python convert.py
  ```
  This will export your code for each question into a `.py` file.
    - **Note**: if you want to add more cells, add this to the **first** line of the cell:
  ```python
  # Q5_graded
  ```
  according to the question number.
  - There are 2 assignments in Gradescope:

    ![assignments](https://i.ibb.co/10GMhGM/Screen-Shot-2021-03-21-at-02-16-25.png)
  
    You should upload your **codes** and your **notebook** in `HW3` section and your final report for all of the questions as a **single pdf** file in `HW3 - Report`. Autograder will automatically check for:
    - `CI992_HW3.ipynb`
    - `Q1.2.py`
    - `Q1.3.py`
    - `inverted_pendulum.fcl`
    - Your name and ID in the beginning of `.ipynb` file.

    It is important that you <font color='red'>**don't**</font> change the names of these files before submission.

4. If you pass the autograder, you're good to go.